export type Country = { code: string; name: string; dialCode: string; flag: string };

// Turkey listed first as the default; the rest follow roughly by relevance
// to Perla Marine's customer base (Europe, Mediterranean/Black Sea region,
// then the rest of the world).
export const COUNTRIES: Country[] = [
  { code: "TR", name: "Türkiye", dialCode: "90", flag: "🇹🇷" },
  { code: "DE", name: "Almanya", dialCode: "49", flag: "🇩🇪" },
  { code: "US", name: "Amerika Birleşik Devletleri", dialCode: "1", flag: "🇺🇸" },
  { code: "GB", name: "Birleşik Krallık", dialCode: "44", flag: "🇬🇧" },
  { code: "FR", name: "Fransa", dialCode: "33", flag: "🇫🇷" },
  { code: "NL", name: "Hollanda", dialCode: "31", flag: "🇳🇱" },
  { code: "IT", name: "İtalya", dialCode: "39", flag: "🇮🇹" },
  { code: "ES", name: "İspanya", dialCode: "34", flag: "🇪🇸" },
  { code: "GR", name: "Yunanistan", dialCode: "30", flag: "🇬🇷" },
  { code: "RU", name: "Rusya", dialCode: "7", flag: "🇷🇺" },
  { code: "UA", name: "Ukrayna", dialCode: "380", flag: "🇺🇦" },
  { code: "AT", name: "Avusturya", dialCode: "43", flag: "🇦🇹" },
  { code: "BE", name: "Belçika", dialCode: "32", flag: "🇧🇪" },
  { code: "CH", name: "İsviçre", dialCode: "41", flag: "🇨🇭" },
  { code: "SE", name: "İsveç", dialCode: "46", flag: "🇸🇪" },
  { code: "NO", name: "Norveç", dialCode: "47", flag: "🇳🇴" },
  { code: "DK", name: "Danimarka", dialCode: "45", flag: "🇩🇰" },
  { code: "FI", name: "Finlandiya", dialCode: "358", flag: "🇫🇮" },
  { code: "PL", name: "Polonya", dialCode: "48", flag: "🇵🇱" },
  { code: "PT", name: "Portekiz", dialCode: "351", flag: "🇵🇹" },
  { code: "IE", name: "İrlanda", dialCode: "353", flag: "🇮🇪" },
  { code: "CZ", name: "Çekya", dialCode: "420", flag: "🇨🇿" },
  { code: "RO", name: "Romanya", dialCode: "40", flag: "🇷🇴" },
  { code: "BG", name: "Bulgaristan", dialCode: "359", flag: "🇧🇬" },
  { code: "HR", name: "Hırvatistan", dialCode: "385", flag: "🇭🇷" },
  { code: "HU", name: "Macaristan", dialCode: "36", flag: "🇭🇺" },
  { code: "SK", name: "Slovakya", dialCode: "421", flag: "🇸🇰" },
  { code: "SI", name: "Slovenya", dialCode: "386", flag: "🇸🇮" },
  { code: "RS", name: "Sırbistan", dialCode: "381", flag: "🇷🇸" },
  { code: "AL", name: "Arnavutluk", dialCode: "355", flag: "🇦🇱" },
  { code: "MK", name: "Kuzey Makedonya", dialCode: "389", flag: "🇲🇰" },
  { code: "ME", name: "Karadağ", dialCode: "382", flag: "🇲🇪" },
  { code: "BA", name: "Bosna Hersek", dialCode: "387", flag: "🇧🇦" },
  { code: "CY", name: "Kıbrıs", dialCode: "357", flag: "🇨🇾" },
  { code: "MT", name: "Malta", dialCode: "356", flag: "🇲🇹" },
  { code: "LU", name: "Lüksemburg", dialCode: "352", flag: "🇱🇺" },
  { code: "IS", name: "İzlanda", dialCode: "354", flag: "🇮🇸" },
  { code: "EE", name: "Estonya", dialCode: "372", flag: "🇪🇪" },
  { code: "LV", name: "Letonya", dialCode: "371", flag: "🇱🇻" },
  { code: "LT", name: "Litvanya", dialCode: "370", flag: "🇱🇹" },
  { code: "MD", name: "Moldova", dialCode: "373", flag: "🇲🇩" },
  { code: "BY", name: "Belarus", dialCode: "375", flag: "🇧🇾" },
  { code: "AZ", name: "Azerbaycan", dialCode: "994", flag: "🇦🇿" },
  { code: "GE", name: "Gürcistan", dialCode: "995", flag: "🇬🇪" },
  { code: "AM", name: "Ermenistan", dialCode: "374", flag: "🇦🇲" },
  { code: "KZ", name: "Kazakistan", dialCode: "7", flag: "🇰🇿" },
  { code: "UZ", name: "Özbekistan", dialCode: "998", flag: "🇺🇿" },
  { code: "TM", name: "Türkmenistan", dialCode: "993", flag: "🇹🇲" },
  { code: "KG", name: "Kırgızistan", dialCode: "996", flag: "🇰🇬" },
  { code: "TJ", name: "Tacikistan", dialCode: "992", flag: "🇹🇯" },
  { code: "AE", name: "Birleşik Arap Emirlikleri", dialCode: "971", flag: "🇦🇪" },
  { code: "SA", name: "Suudi Arabistan", dialCode: "966", flag: "🇸🇦" },
  { code: "QA", name: "Katar", dialCode: "974", flag: "🇶🇦" },
  { code: "KW", name: "Kuveyt", dialCode: "965", flag: "🇰🇼" },
  { code: "BH", name: "Bahreyn", dialCode: "973", flag: "🇧🇭" },
  { code: "OM", name: "Umman", dialCode: "968", flag: "🇴🇲" },
  { code: "IL", name: "İsrail", dialCode: "972", flag: "🇮🇱" },
  { code: "JO", name: "Ürdün", dialCode: "962", flag: "🇯🇴" },
  { code: "LB", name: "Lübnan", dialCode: "961", flag: "🇱🇧" },
  { code: "IQ", name: "Irak", dialCode: "964", flag: "🇮🇶" },
  { code: "IR", name: "İran", dialCode: "98", flag: "🇮🇷" },
  { code: "EG", name: "Mısır", dialCode: "20", flag: "🇪🇬" },
  { code: "LY", name: "Libya", dialCode: "218", flag: "🇱🇾" },
  { code: "TN", name: "Tunus", dialCode: "216", flag: "🇹🇳" },
  { code: "DZ", name: "Cezayir", dialCode: "213", flag: "🇩🇿" },
  { code: "MA", name: "Fas", dialCode: "212", flag: "🇲🇦" },
  { code: "ZA", name: "Güney Afrika", dialCode: "27", flag: "🇿🇦" },
  { code: "NG", name: "Nijerya", dialCode: "234", flag: "🇳🇬" },
  { code: "KE", name: "Kenya", dialCode: "254", flag: "🇰🇪" },
  { code: "CN", name: "Çin", dialCode: "86", flag: "🇨🇳" },
  { code: "JP", name: "Japonya", dialCode: "81", flag: "🇯🇵" },
  { code: "KR", name: "Güney Kore", dialCode: "82", flag: "🇰🇷" },
  { code: "IN", name: "Hindistan", dialCode: "91", flag: "🇮🇳" },
  { code: "PK", name: "Pakistan", dialCode: "92", flag: "🇵🇰" },
  { code: "BD", name: "Bangladeş", dialCode: "880", flag: "🇧🇩" },
  { code: "ID", name: "Endonezya", dialCode: "62", flag: "🇮🇩" },
  { code: "MY", name: "Malezya", dialCode: "60", flag: "🇲🇾" },
  { code: "SG", name: "Singapur", dialCode: "65", flag: "🇸🇬" },
  { code: "TH", name: "Tayland", dialCode: "66", flag: "🇹🇭" },
  { code: "VN", name: "Vietnam", dialCode: "84", flag: "🇻🇳" },
  { code: "PH", name: "Filipinler", dialCode: "63", flag: "🇵🇭" },
  { code: "AU", name: "Avustralya", dialCode: "61", flag: "🇦🇺" },
  { code: "NZ", name: "Yeni Zelanda", dialCode: "64", flag: "🇳🇿" },
  { code: "CA", name: "Kanada", dialCode: "1", flag: "🇨🇦" },
  { code: "MX", name: "Meksika", dialCode: "52", flag: "🇲🇽" },
  { code: "BR", name: "Brezilya", dialCode: "55", flag: "🇧🇷" },
  { code: "AR", name: "Arjantin", dialCode: "54", flag: "🇦🇷" },
  { code: "CL", name: "Şili", dialCode: "56", flag: "🇨🇱" },
  { code: "CO", name: "Kolombiya", dialCode: "57", flag: "🇨🇴" },
  { code: "PE", name: "Peru", dialCode: "51", flag: "🇵🇪" },
  { code: "VE", name: "Venezuela", dialCode: "58", flag: "🇻🇪" },
];

export const DEFAULT_COUNTRY_CODE = "TR";
